@echo off
echo Cleaning up generated files and folders...

REM Remove generated deployment packages
if exist deployment-package rmdir /s /q deployment-package
if exist sharepoint-package rmdir /s /q sharepoint-package
if exist excel-package rmdir /s /q excel-package
if exist github-package rmdir /s /q github-package

REM Remove generated zip files
if exist sharepoint-package.zip del sharepoint-package.zip

REM Remove generated manifest files
if exist manifest-deployment-template.xml del manifest-deployment-template.xml

REM Remove build artifacts
if exist dist rmdir /s /q dist

echo.
echo ================================
echo Cleanup completed!
echo ================================
echo.
echo The following folders/files were removed:
echo - deployment-package/
echo - sharepoint-package/
echo - excel-package/
echo - github-package/
echo - sharepoint-package.zip
echo - manifest-deployment-template.xml
echo - dist/
echo.
echo These folders are excluded in .gitignore and will be regenerated by build scripts.
echo.

pause